#!/usr/bin/env bash
# script that will display information about subdomains.

domain_info () {	
	record=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
	ip=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
	
	echo "The subdomain $2 is a $record record and points to $ip"

	return 0
}

if [ -z "$2" ]
then
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"
else 
	domain_info "$1" "$2"
fi
