#!/usr/bin/env bash
# bash to install nginx on a remote server

sudo apt-get update
sudo apt-get -y install nginx
sudo systemctl start nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" >> /var/www/html/index.nginx-debian.html
