#!/usr/bin/env bash
# bash to install nginx on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://google.com permanent;' /etc/nginx/sites-enabled/default
sudo service nginx start

