#!/usr/bin/env bash
# script that configures the HAProxy and creates a load balancer for 2 web servers

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*

sudo sed -i "$ a \ \nfrontend localnodes\n \tbind *:80\n \tmode http\n \tdefault_backend nodes\n \nbackend nodes\n \tmode http\n \tbalance roundrobin\n \tserver 1223-web-01 104.196.49.8 check\n \tserver 1223-web-02 54.210.155.251 check\n" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
