#!/usr/bin/env bash
# script to make nginx listen to port 80

sudo sed -i "\ server {\ a \ \tlisten 80 default_server;" /etc/nginx/sites-enabled/default

sudo sed -i "\ http {\ a \ \tlisten 80 default_server;" /etc/nginx/nginx.conf

sudo service nginx restart
