#!/usr/bin/env bash
# write a Bash script that gives you information about the holbertonschool file.
file=holbertonschool

if [ -e "$file" ]; then
	echo "holbertonschool file exists"
	if test -s "$file"; then
		echo "holbertonschool file is not empty"
		if test -f "$file"; then
			echo "holbertonschool is a regular file"
		fi;
	else
		echo "holbertonschool file is empty"
		if test -f "$file"; then
			echo "holbertonschool is a regular file"
		fi;
	fi;
else
	echo "holbertonschool file does not exist"
fi;
