#!/usr/bin/env bash
# transfers a file from our client to a server
if [ $# -lt 1 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/holberton "$1" ubuntu@104.196.49.8:~/
fi
