#!/usr/bin/env bash
# script that configures an Ubuntu server
cp -f ~/hosts.new /etc/hosts
sed -i 's/127.0.0.1 127.0.0.2/' ~/hosts.new
sed -i 's/8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
