#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
sudo chown -R nginx:nginx /etc/nginx/
sudo chmod 744 -R /etc/nginx
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;/' /etc/nginx/sites-available/default
sudo ed -i 's+pid /run/nginx.pid;+pid /tmp/nginx.pid;+' /etc/nginx/nginx.conf
sudo -u service nginx restart
