#!/usr/bin/env bash
# new user nginx
sudo pkill -f apache2
sudo chmod 755 /etc/nginx/
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
